# GitHub Sponsors & Donations
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors (Preferred - 0% fees for personal accounts)
github: ludovicsanchez38-creator

# Alternative platforms (uncomment if needed)
# patreon: YourPatreonUsername
# ko_fi: YourKoFiUsername
# buy_me_a_coffee: YourBuyMeACoffeeUsername
# liberapay: YourLiberapayUsername
# custom: ['https://synoptia.fr/donate', 'https://yourwebsite.com/support']
